# Generated by Django 5.0.1 on 2024-02-12 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('Car Owner', 'Car Owner'), ('Technician', 'Technician')], max_length=20),
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
