# Generated by Django 5.0.1 on 2024-01-24 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_carowner_car_repairrequest_technician_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technician',
            name='expertise',
        ),
        migrations.RemoveField(
            model_name='technician',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='technician',
            name='longitude',
        ),
        migrations.AddField(
            model_name='technician',
            name='availability',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
