# Generated by Django 5.0.1 on 2024-02-12 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_userprofile_user_type_delete_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('owner', 'Car Owner'), ('technician', 'Technician')], max_length=20),
        ),
    ]
